baseURL = "http://asubiotto.com/"
languageCode = "en-us"
title = "Alfonso Subiotto"
theme = "hello-friend-ng"
googleAnalytics = "G-4J888DE1QK"

[params]
    homeSubtitle = "Software Engineer & Investor"

    [[params.social]]
        name = "twitter"
        url  = "https://twitter.com/asubiotto"

    [[params.social]]
        name = "linkedin"
        url  = "https://linkedin.com/in/asubiotto"

    [[params.social]]
        name = "bluesky"
        url  = "https://bsky.app/profile/asubiotto.bsky.social"

    [[params.social]]
        name = "github"
        url  = "https://github.com/asubiotto"

    [[params.social]]
        name = "email"
        url  = "mailto:alfonsojssm+website@gmail.com"

[menu]
    [[menu.main]]
        name = "Home"
        weight = 1
        identifier = "_home"
        pageRef = "/"
    [[menu.main]]
        name = "About"
        weight = 2
        identifier = "about"
        pageRef = "about/"

# Jobs commented out; difficult to keep updated.
#    [[menu.main]]
#        identifier = "jobs"
#        name = "Jobs"
#        url = "jobs/"
#        weight = "4"
