baseURL = "http://asubiotto.com/"
languageCode = "en-us"
title = "Alfonso Subiotto"
theme = "hello-friend-ng"
googleAnalytics = "G-4J888DE1QK"

[params]
    homeSubtitle = "Operator Angel & Technical Startup Advisor"

    [[params.social]]
        name = "twitter"
        url  = "https://twitter.com/asubiotto"

    [[params.social]]
        name = "linkedin"
        url  = "https://linkedin.com/in/asubiotto"

    [[params.social]]
        name = "github"
        url  = "https://github.com/asubiotto"

    [[params.social]]
        name = "email"
        url  = "mailto:alfonsojssm+website@gmail.com"

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = "1"

    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "about/"
        weight = "0"

    [[menu.main]]
        identifier = "jobs"
        name = "Jobs"
        url = "jobs/"
        weight = "0"